language: python
python:
  - "2.7"
  - "2.6"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
    - sudo apt-get -y update
    - sudo apt-get -y install openssl python-dev swig
    - python setup.py develop
    - pip install Babel lingua pylibmc moto
    - sudo apt-get -y install npm
    - npm install
# command to run tests, e.g. python setup.py test
script:
    - python setup.py test
    - grunt karma:ci
    - grunt jshint 
after_script: python setup.py extract_messages

